# Generated by Django 4.0.2 on 2022-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mev', '0002_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pics',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
