# Generated by Django 4.0.2 on 2022-02-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mev', '0003_post_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pics',
            field=models.CharField(max_length=255),
        ),
    ]
