# Generated by Django 4.0.2 on 2022-02-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mev', '0004_alter_post_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
