# Generated by Django 4.0.2 on 2022-02-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mev', '0006_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
