# Generated by Django 4.0.2 on 2022-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mev', '0008_post_likes_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Eastern Atlantic Division', 'Eastern Atlantic Division'), ('Eastern Metropolitan Division', 'Eastern Metropolitan Division'), ('Western Central Division', 'Western Central Division'), ('Western Pacific Division', 'Western Pacific Division')], max_length=255),
        ),
    ]
